/*
Kaylub Murphy
03/03/2025
Purpose: Create a program that compares two strings and checks if the user input can be made from the
random letters that were given
 */

import java.util.HashMap;
import java.util.Map;
import java.util.Random;
import java.util.Scanner;

public class Main {

    //Creates a string builder method
    public static StringBuilder generateLetters() {
        //Random number generator
        Random randomLetters = new Random();

        //Creates a string builder
        StringBuilder stringOfLetters = new StringBuilder();

        //For loop runs 7 times, producing 7 letters
        for (int i = 0; i < 7; i++) {
            //Each run (7 times) a random number between 0-25 is generated.
            //A represents 65 in ASCII, so it really gives you a number from 65-90
            //65-90 represent the capital letters of the alphabet, so those are what are generated
            char c = (char) (randomLetters.nextInt(26) + 'A');
            //Adds each character to the string builder
            stringOfLetters.append(c);
        }
        //Returns the string builder
        return stringOfLetters;
    }

    //Sets the two strings given (the letters generated and the user input) to lettersGiven and lettersEntered
    public static boolean canSpell(String lettersGiven, String lettersEntered) {

        //Creates a hashmap of the character as the key, and it's integer as the value
        Map<Character, Integer> tileCount = new HashMap<>();
        //Turns the lettersGiven string to a character array called scrabbleTiles
        for (char scrabbleTiles : lettersGiven.toCharArray()) {
            //Looks up the values of each of the scrabbleTiles according to the tileCount map
            //If it exists then it will add 1 to the count, otherwise it returns 0
            tileCount.put(scrabbleTiles, tileCount.getOrDefault(scrabbleTiles, 0) + 1);
        }

        //Turns the lettersEntered string to a character array called checkLettersMatch
        for (char checkLettersMatch : lettersEntered.toCharArray()) {
            //Each letter is checked. If a letter in the checkLettersMatch array is not found or if it is
            //found, but it's been set to 0 (meaning that it's been used up) it will return false
            if (!tileCount.containsKey(checkLettersMatch) || tileCount.get(checkLettersMatch) == 0) {
                return false;
            }
            //Each time a tile is used its value will go down by 1. That way when it reaches 0, and it is called
            //again, the if loop will return false
            tileCount.put(checkLettersMatch, tileCount.get(checkLettersMatch) - 1);
        }
        //If everything works, the program returns true
        return true;
    }

    public static void main(String[] args) {

        Scanner input = new Scanner(System.in);
        //Takes the letters generated by the generateLetters() String Builder and turns them into a single string
        String scrabbleLetters = String.valueOf(generateLetters());

        System.out.println("Here are your scrabble letters: " + scrabbleLetters);
        System.out.print("Enter a word you can spell from these: ");
        //Takes user input and sets it all to upper case
        String userInput = input.nextLine().toUpperCase();

        //System.out.println(canSpell(scrabbleLetters, userInput));
        int i = 0;
        //i is initially 0. While this continues to be true this will loop.
        while (i == 0) {
            //Sends the letters generated and the user input to the can spell method
            //If it comes back true, it will run if, otherwise it will run else
            if (canSpell(scrabbleLetters, userInput)) {
                System.out.println("You have those tiles! (Just make sure it's a real word before you play it!)");
                //With i++ it's no longer true that i==0, so the loop ends
                i++;
            } else {
                //If they can't then it'll ask them to try again
                System.out.println("You can't spell that! Let's try that again: ");
                userInput = input.nextLine().toUpperCase();
            }
        }

    }
}